"""UpAdd comment_count.

Revision ID: ac1981717e6b
Revises: 8d0b35a99e0e
Create Date: 2024-10-30 19:04:46.686535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1981717e6b'
down_revision = '8d0b35a99e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('comment_count')

    # ### end Alembic commands ###
